apiVersion: v1
kind: Service
metadata:
  name: i-mimo-frontend-service
spec:
  type: NodePort
  selector:
    app: i-mimo-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30201 # NodePort mapping for external web access
